/*
 * make-fonts.mjs — regenerates css/fonts-embedded.css.
 *
 * The site ships zero runtime dependencies and must keep working with no
 * third-party requests, so every face is inlined as a base64 woff2 rather
 * than linked from fonts.googleapis.com. This script is the only way that
 * file is produced: don't hand-edit it.
 *
 * Only the `latin` and `latin-ext` subsets are kept. latin carries the
 * German umlauts, latin-ext carries the Turkish g-breve, s-cedilla and
 * dotted capital I. Everything else Google offers (cyrillic, vietnamese)
 * is dead weight for a three-language guest list.
 *
 *   node tools/make-fonts.mjs
 */
import fs from "node:fs/promises";

// Google only serves woff2 to a browser UA; with the default Node one it
// answers with truetype, which is roughly four times the size.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const KEEP = new Set(["latin", "latin-ext"]);

const FAMILIES = [
  // Headings and the names on the green card.
  { family: "Playfair Display", axis: "wght@400;700" },
  // The letter's handwriting: title and sign-off. Monoline and connected,
  // which is what makes the left-to-right reveal read as a pen.
  { family: "Sacramento", axis: "wght@400" },
  // The letter's body.
  { family: "Cormorant Garamond", axis: "wght@300;400" },
];

// Google now serves these as variable fonts: asking for two weights returns
// two @font-face blocks pointing at the *same* file. Embedding per block
// would inline every byte twice, so faces are grouped by URL and emitted
// once with a font-weight range, which is how a variable font should be
// declared anyway.


async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.text();
}

async function fetchBase64(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return Buffer.from(await res.arrayBuffer()).toString("base64");
}

const out = [
  "/* Generated by tools/make-fonts.mjs. Do not edit by hand.",
  " * Self-hosted so the site makes no third-party requests: a guest's",
  " * visit is never visible to anyone but GitHub Pages.",
  " */",
  "",
];

let total = 0;

for (const { family, axis } of FAMILIES) {
  const url =
    "https://fonts.googleapis.com/css2?family=" +
    encodeURIComponent(family).replace(/%20/g, "+") +
    ":" + axis + "&display=swap";
  const css = await fetchText(url);

  // Each @font-face in Google's response is preceded by a /* subset */ comment.
  const faces = new Map(); // woff2 url -> { style, range, weights:Set }
  for (const block of css.split("/*").slice(1)) {
    const subset = block.slice(0, block.indexOf("*/")).trim();
    if (!KEEP.has(subset)) continue;

    const src = /url\((https:[^)]+\.woff2)\)/.exec(block)[1];
    const weight = Number(/font-weight:\s*(\d+)/.exec(block)[1]);
    let face = faces.get(src);
    if (!face) {
      face = {
        style: /font-style:\s*(\w+)/.exec(block)[1],
        range: /unicode-range:\s*([^;]+);/.exec(block)[1].trim(),
        subset: subset,
        weights: new Set(),
      };
      faces.set(src, face);
    }
    face.weights.add(weight);
  }

  for (const [src, face] of faces) {
    const b64 = await fetchBase64(src);
    total += b64.length;

    const weights = [...face.weights].sort((a, b) => a - b);
    // A single weight stays a single weight; several sharing one file means
    // a variable font, so declare the range it actually covers.
    const weightDecl =
      weights.length === 1 ? String(weights[0]) : weights[0] + " " + weights[weights.length - 1];

    console.log(
      `  ${family} ${weightDecl} ${face.subset}  ${Math.round(b64.length / 1024)} KB`
    );

    out.push(
      "@font-face {",
      `  font-family: '${family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${weightDecl};`,
      "  font-display: swap;",
      `  src: url(data:font/woff2;base64,${b64}) format('woff2');`,
      `  unicode-range: ${face.range};`,
      "}"
    );
  }
}

await fs.writeFile(
  new URL("../css/fonts-embedded.css", import.meta.url),
  out.join("\n") + "\n"
);
console.log(`\ncss/fonts-embedded.css written, ${Math.round(total / 1024)} KB of base64`);
